image: Ubuntu1804  # образ для сборки

stack: node 14  # окружение

cache: node_modules  # кеширование

environment:
  access_token:
    secure: w4mfDcktrSV1PCcXouDb0LxkYgApS6TwJNo32I/L6hPWVeDb44ERjSnSyPk2+/1y

for:
-
  branches:
    except:
      - master

  install:
    - npm install  # команда установки зависимостей

  build: off  # отключаем встроенную в appveyor систему сборки

  build_script:
    - npm run build   # команда сборки

  deploy_script:
    - git config --global credential.helper store
    - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
    - git config --global user.email "a.shleyko@yandex.ru"
    - git config --global user.name "Alexandr Shleyko"
    - bash ./deploy.sh

-
  branches:
    only:
      - master

  install:
    - npm install  # команда установки зависимостей

  build: off  # отключаем встроенную в appveyor систему сборки

  build_script:
    - npm run build   # команда сборки
