image: Ubuntu1804  # образ для сборки

stack: node 14  # окружение

cache: node_modules  # кеширование

for:
-
  branches:
    only:
      - master

  install:
    - npm install  # команда установки зависимостей

  build: off  # отключаем встроенную в appveyor систему сборки

  build_script:
    - npm run build   # команда сборки

  deploy_script:
    - bash ./deploy.sh

-
  branches:
    except:
      - master

  install:
    - npm install  # команда установки зависимостей

  build: off  # отключаем встроенную в appveyor систему сборки

  build_script:
    - npm run build   # команда сборки
