image: Ubuntu1804

stack: node 14

cache: node_modules

environment:
  access_token:
    secure: w4mfDcktrSV1PCcXouDb0LxkYgApS6TwJNo32I/L6hPWVeDb44ERjSnSyPk2+/1y

for:
-
  branches:
    except:
      - master

  install:
    - npm install

  build: off

  build_script:
    - npm run build   # команда сборки

  deploy_script:
    - bash ./deploy.sh

-
  branches:
    only:
      - master

  install:
    - npm install  # команда установки зависимостей

  build: off  # отключаем встроенную в appveyor систему сборки

  build_script:
    - npm run build   # команда сборки
